ALTER TABLE objects
    ADD COLUMN IF NOT EXISTS bbox_x      INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS bbox_y      INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS bbox_width  INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS bbox_height INTEGER NOT NULL DEFAULT 0;