from __future__ import annotations

from typing import Optional, List
from app.domain.search_job import SearchJob
from app.domain.value_objects import SearchJobId


class SearchJobRepository:
    async def create(self, job: SearchJob) -> None: ...
    async def update_progress(self, job_id: SearchJobId, value: float) -> None: ...
    async def update_status(self, job_id: SearchJobId, status: str, error: Optional[str]) -> None: ...
    async def find_all(self) -> List[SearchJob]: ...
    async def find_by_id(self, job_id: SearchJobId) -> Optional[SearchJob]: ...
